"""
Step 0b: Call DeepSeek API to segment treatment histories into discrete plans.

Reads patient prompt files generated by step0a, sends them to DeepSeek-chat,
and extracts structured JSON treatment plans from the responses.
"""
import os
import time
import json
import re
import glob
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from openai import OpenAI

from config import (
    SEGMENTATION_PROMPTS_DIR, TREATMENT_PLANS_DIR, TREATMENT_REGIMENS_DIR,
    API_KEY, API_BASE_URL, API_MODEL_SEGMENTATION,
    SEGMENTATION_TEMPERATURE, SEGMENTATION_TOP_P,
    MAX_WORKERS, RATE_LIMIT_DELAY,
)
from utils import RateLimiter

# Global rate limiter
rate_limiter = RateLimiter(RATE_LIMIT_DELAY)


def setup_api_client():
    """Set up and return the OpenAI-compatible API client."""
    if not API_KEY:
        raise ValueError("Environment variable DEEPSEEK_API_KEY must be set")
    return OpenAI(api_key=API_KEY, base_url=API_BASE_URL)


def extract_patient_id(file_path):
    """Extract patient ID from prompt filename."""
    match = re.search(r"(P-\d+)_prompt\.txt", os.path.basename(file_path))
    return match.group(1) if match else None


def model_api_request(client, prompt_text, max_retries=5):
    """Call DeepSeek API and return (extracted_json_str, full_response)."""
    for attempt in range(max_retries):
        try:
            rate_limiter.acquire()
            response = client.chat.completions.create(
                model=API_MODEL_SEGMENTATION,
                messages=[{'role': 'user', 'content': prompt_text}],
                stream=True,
                temperature=SEGMENTATION_TEMPERATURE,
                top_p=SEGMENTATION_TOP_P,
            )

            generated_text = ""
            for chunk in response:
                delta = chunk.choices[0].delta
                if hasattr(delta, "content") and delta.content:
                    generated_text += delta.content

            if not generated_text.strip():
                raise Exception("Empty output received.")

            # Try to extract JSON from code block
            json_match = re.search(r'```json\s*([\s\S]*?)\s*```', generated_text)
            if json_match:
                json_str = json_match.group(1).strip()
                try:
                    json.loads(json_str)  # validate
                    return json_str, generated_text
                except json.JSONDecodeError:
                    return None, generated_text
            return None, generated_text

        except Exception as e:
            error_str = str(e)
            if "TPM limit reached" in error_str or "429" in error_str:
                print(f"[Thread] Rate limit hit, waiting 60s (attempt {attempt+1})")
                time.sleep(60)
            else:
                wait_time = 2 ** attempt
                print(f"[Thread] Request failed: {error_str} (attempt {attempt+1}), waiting {wait_time}s")
                time.sleep(wait_time)

    return None, "Failed after multiple retries"


def extract_json_from_text(text):
    """Best-effort JSON extraction from unstructured text."""
    # Try code block first
    json_match = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', text)
    if json_match:
        try:
            return json.loads(json_match.group(1).strip())
        except json.JSONDecodeError:
            pass

    # Try raw JSON object
    json_match = re.search(r'({[\s\S]*})', text)
    if json_match:
        json_str = json_match.group(1).strip()
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            # Fix common issues
            json_str = re.sub(r"'([^']*)':", r'"\1":', json_str)
            json_str = re.sub(r',\s*}', '}', json_str)
            json_str = re.sub(r',\s*]', ']', json_str)
            try:
                return json.loads(json_str)
            except json.JSONDecodeError:
                pass

    return None


def process_one_prompt(client, file_path):
    """Process a single prompt file and save structured treatment plan."""
    patient_id = extract_patient_id(file_path)
    if not patient_id:
        return {"error": f"Could not extract patient ID from file: {file_path}"}

    with open(file_path, "r", encoding="utf-8") as f:
        prompt_text = f.read()

    json_str, full_response = model_api_request(client, prompt_text)

    if json_str is None:
        treatment_plan = extract_json_from_text(full_response)
    else:
        try:
            treatment_plan = json.loads(json_str)
        except json.JSONDecodeError:
            treatment_plan = extract_json_from_text(full_response)

    result = {
        "patient_id": patient_id,
        "treatment_plan": treatment_plan if treatment_plan else {"error": "Failed to extract valid JSON"},
    }
    api_output = {
        "patient_id": patient_id,
        "full_api_response": full_response,
        "extracted_json": treatment_plan,
    }

    # Save result files
    with open(os.path.join(TREATMENT_PLANS_DIR, f"{patient_id}_treatment.json"), "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    with open(os.path.join(TREATMENT_REGIMENS_DIR, f"{patient_id}_api_response.json"), "w", encoding="utf-8") as f:
        json.dump(api_output, f, indent=2, ensure_ascii=False)

    return result


def main():
    os.makedirs(TREATMENT_PLANS_DIR, exist_ok=True)
    os.makedirs(TREATMENT_REGIMENS_DIR, exist_ok=True)

    client = setup_api_client()
    prompt_files = glob.glob(os.path.join(SEGMENTATION_PROMPTS_DIR, "*_prompt.txt"))
    print(f"Found {len(prompt_files)} prompt files")

    results = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_file = {executor.submit(process_one_prompt, client, f): f for f in prompt_files}
        for future in tqdm(as_completed(future_to_file), total=len(prompt_files), desc="Generating treatment plans"):
            try:
                results.append(future.result())
            except Exception as e:
                pid = extract_patient_id(future_to_file[future]) or "unknown"
                print(f"[Error] {pid}: {e}")

    # Summary
    successful = sum(1 for r in results if "error" not in r.get("treatment_plan", {}))
    failed = len(results) - successful
    print(f"Treatment plan generation complete: {successful} successful, {failed} failed")

    summary = {
        "total_files": len(prompt_files),
        "successful": successful,
        "failed": failed,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "configuration": {
            "api_model": API_MODEL_SEGMENTATION,
            "temperature": SEGMENTATION_TEMPERATURE,
            "top_p": SEGMENTATION_TOP_P,
            "max_workers": MAX_WORKERS,
        },
    }
    with open(os.path.join(TREATMENT_PLANS_DIR, "treatment_generation_summary.json"), "w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
